//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRecording
    {
        public int ID { get; set; }
        public int IdClient { get; set; }
        public int IdRecording { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Recording Recording { get; set; }
    }
}
