//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recording()
        {
            this.ClientRecording = new HashSet<ClientRecording>();
        }
    
        public int IdRecording { get; set; }
        public string DateRecording { get; set; }
        public string TimeRecording { get; set; }
        public int IdService { get; set; }
        public int IdWorker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRecording> ClientRecording { get; set; }
        public virtual Service Service { get; set; }
        public virtual WorkerPost WorkerPost { get; set; }
    }
}
