//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording
    {
        public int IdRecording { get; set; }
        public Nullable<int> IdClient { get; set; }
        public int IdService { get; set; }
        public Nullable<int> IdWorker { get; set; }

        public string CLIENT { get => $"{Client.FName}"; }
        public string SERVICE { get => $"{Service.NameService}"; }
        public string WORKER { get => $"{Worker.FName} {Worker.LName}"; }

        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
